### ISSUE TITLE
Update fibers to v2

### ISSUE THREAD

**Issue by andrestaht** [xolvio/chimp#683]
#####  Expected behaviour
Chimp works fine with node v8.

#####  Actual behaviour
I get an error while installing dependencies with `yarn install`.

#####  Version & tools:
* Chimp command line used: *chimp*
* Chimp: *0.51.1*
* Node.js: *v8.10.0*
* Java: *1.8.0_65*
* Operation system: *Darwin Kernel Version 17.4.0*

#####  Console / Log Output
```
[ERROR] error /path/to/project/node_modules/fibers: Command failed.
[ERROR] Exit code: 127
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ERROR] Command: node build.js || nodejs build.js
[ERROR] Arguments:
[ERROR] Directory: /path/to/project/node_modules/fibers
[ERROR] Output:
[ERROR] node-gyp not found! Please ensure node-gyp is in your PATH--
[ERROR] Try running: `sudo npm install -g node-gyp`
[ERROR] spawn node-gyp ENOENT
[ERROR] /bin/sh: nodejs: command not found
```

#####  Solution
This can be solved with upgrading **fibers** to **v2.0.2**.
Update should also be done in the chimp dependencies:
* cucumber-js
* wdio-sync
* xolvio-fiber-utils
* xolvio-sync-webdriverio

**Comment by kwuite** [comment]
@andrestaht did you remove node_modules folder and reinstalled everything after moving to node V8? I had the exact same problem and after removing and reinstalling everything (with fresh cache), my problem was solved.

**Comment by samhatoum** [comment]
hey @andrestaht sorry I've been slammed. I'll get to this ASAP

**Comment by andrestaht** [comment]
@kwuite yes, after updating node I did a fresh install.
Tried it again and indeed `yarn install` now works.
Even with Chimp 0.49.0.

But when building with maven using https://github.com/eirslett/frontend-maven-plugin I still get the same error.

Both using node v8.10.0 and yarn v1.3.2.

**Comment by andrestaht** [comment]
Seems to be an issue with frontend-maven-plugin - https://github.com/eirslett/frontend-maven-plugin/issues/667
